<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE authors [
<!ELEMENT authors (author)*>
<!ELEMENT author (name , nick , email , role+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nick (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT role (#PCDATA)>
]>

<!-- if you modify this file, be sure it's still valid - xmllint is your friend
-->

<authors>
	<author>
		<name>Dvornik, László</name>
		<nick>laci</nick>
		<email>dvornik@gnome.hu</email>
		<role>0.2 maintainer from April 2005 to August 2005</role>
		<role>GNOME maintainer from November 2004 to April 2005</role>
	</author>
	<author>
		<name>Katona, Vilmos</name>
		<nick>Shrift</nick>
		<email>shrift@linuxforum.hu</email>
		<role>packager from November 2004 to June 2005</role>
		<role>forum administrator from February 2005 to June 2005</role>
	</author>
	<author>
		<name>Mauras, Olivier</name>
		<nick>Tuxbubling</nick>
		<email>tuxbubling@tiscali.fr</email>
		<role>package maintainer from August 2005 to December 2005</role>
	</author>
	<author>
		<name>Zlehovszky, Ádám</name>
		<nick>zleho</nick>
		<email>zleho@index.hu</email>
		<role>apps and x11 category maintainer from October 2004 to June 2005</role>
	</author>
</authors>
