<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE volumes [
<!ELEMENT volumes (fst_root , out_dir? , version? , codename? , volume+)>
<!ELEMENT volume (arch? , media , serial? , size?)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT arch (#PCDATA)>
<!ELEMENT media (#PCDATA)>
<!ELEMENT serial (#PCDATA)>
<!ELEMENT size (#PCDATA)>
]>

<volumes>
	<fst_root>/home/ftp/pub/frugalware/frugalware-current</fst_root>
	<out_dir>/home/ftp/pub/frugalware/frugalware-current-iso</out_dir>
	<volume>
		<arch>i686</arch>
		<media>net</media>
	</volume>
	<volume>
		<arch>i686</arch>
		<media>cd</media>
		<serial>1</serial>
	</volume>
	<volume>
		<arch>i686</arch>
		<media>cd</media>
		<serial>2</serial>
	</volume>
	<volume>
		<arch>i686</arch>
		<media>cd</media>
		<serial>3</serial>
	</volume>
	<volume>
		<arch>i686</arch>
		<media>cd</media>
		<serial>4</serial>
	</volume>
	<volume>
		<arch>i686</arch>
		<media>cd</media>
		<serial>5</serial>
	</volume>
	<volume>
		<arch>i686</arch>
		<media>cd</media>
		<serial>6</serial>
	</volume>
	<volume>
		<arch>i686</arch>
		<media>cd</media>
		<serial>7</serial>
	</volume>
	<volume>
		<arch>i686</arch>
		<media>cd</media>
		<serial>8</serial>
	</volume>
	<volume>
		<arch>i686</arch>
		<media>dvd</media>
		<serial>1</serial>
	</volume>
	<volume>
		<arch>i686</arch>
		<media>dvd</media>
		<serial>2</serial>
	</volume>
</volumes>
